"""
PDF report generation service.

Responsibilities:
- Render Mermaid diagrams to PNG images via the Mermaid CLI (``mmdc``).
- Convert LLM-generated Markdown into a structured ReportLab PDF document.
- Upload the completed PDF to S3 and return a presigned download URL.

This module is intentionally separate from ``file_storage.py`` so that PDF
generation concerns (Mermaid, ReportLab, S3 upload) are isolated from the
general file-storage bookkeeping concern.
"""

import logging
import os
import re
import subprocess
import tempfile
import uuid
from pathlib import Path

from botocore.exceptions import ClientError
from reportlab.lib import utils
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer

from app.config import settings
from app.services.aws_service import BUCKET, s3_client

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# ReportLab paragraph styles
# ---------------------------------------------------------------------------

_styles = getSampleStyleSheet()

cover_style = ParagraphStyle(
    "CoverTitle",
    parent=_styles["Title"],
    alignment=TA_CENTER,
    fontSize=28,
    leading=34,
)

heading1_style = ParagraphStyle(
    "Heading1Custom",
    parent=_styles["Heading1"],
    spaceBefore=12,
    spaceAfter=8,
)

heading2_style = ParagraphStyle(
    "Heading2Custom",
    parent=_styles["Heading2"],
    spaceBefore=10,
    spaceAfter=6,
)

heading3_style = ParagraphStyle(
    "Heading3Custom",
    parent=_styles["Heading3"],
    spaceBefore=8,
    spaceAfter=4,
)

body_style = ParagraphStyle(
    "BodyCustom",
    parent=_styles["BodyText"],
    leftIndent=0,
    rightIndent=0,
    firstLineIndent=0,
    spaceAfter=4,
)

bullet_style = ParagraphStyle(
    "BulletCustom",
    parent=body_style,
    leftIndent=20,
    bulletIndent=10,
)

# ---------------------------------------------------------------------------
# Mermaid rendering
# ---------------------------------------------------------------------------

# Resolve the bundled Puppeteer config.  The env var ``PUPPETEER_CONFIG_PATH``
# (mapped to ``settings.puppeteer_config_path``) overrides the default.
_DEFAULT_PUPPETEER_CONFIG = Path(__file__).resolve().parent / "puppeteer-config.json"


def _get_puppeteer_config_path() -> str:
    if settings.puppeteer_config_path:
        return settings.puppeteer_config_path
    return str(_DEFAULT_PUPPETEER_CONFIG)


def render_mermaid_to_png(mermaid_code: str) -> tuple[str, str]:
    """Render a Mermaid diagram string to a PNG file via the ``mmdc`` CLI.

    Args:
        mermaid_code: Raw Mermaid diagram source (without fence markers).

    Returns:
        ``(png_file_path, mmd_file_path)`` — both are temporary files that the
        caller is responsible for cleaning up.

    Raises:
        RuntimeError: If ``mmdc`` exits with a non-zero status or the PNG is
            not produced.
    """
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".mmd",
        delete=False,
        encoding="utf-8",
    ) as f:
        f.write(mermaid_code.strip())
        mmd_file = f.name

    png_file = mmd_file.replace(".mmd", ".png")
    puppeteer_config = _get_puppeteer_config_path()

    result = subprocess.run(
        ["mmdc", "-p", puppeteer_config, "-i", mmd_file, "-o", png_file, "-b", "white"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(f"Mermaid rendering failed:\n{result.stderr}")

    if not os.path.exists(png_file):
        raise RuntimeError("PNG file was not generated by mmdc.")

    return png_file, mmd_file


# ---------------------------------------------------------------------------
# ReportLab helpers
# ---------------------------------------------------------------------------


def fit_image(path: str, max_width: float, max_height: float = 450) -> Image:
    """Scale an image to fit within the given dimensions, preserving aspect ratio."""
    img = utils.ImageReader(path)
    orig_width, orig_height = img.getSize()

    ratio = min(max_width / orig_width, max_height / orig_height, 1.0)
    scaled = Image(path, width=orig_width * ratio, height=orig_height * ratio)
    return scaled


def _markdown_to_reportlab(text: str) -> str:
    """Convert a subset of Markdown inline syntax to ReportLab XML tags."""
    text = text.replace("&", "&amp;")
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    return text


# ---------------------------------------------------------------------------
# S3 helpers
# ---------------------------------------------------------------------------


def _get_presigned_url(file_id: str) -> str | None:
    """Return a presigned GET URL for the original file stored under *file_id*."""
    prefix = f"{file_id}/original/"
    try:
        response = s3_client.list_objects_v2(Bucket=BUCKET, Prefix=prefix)
        objects = response.get("Contents", [])
        if not objects:
            return None

        s3_key = objects[0]["Key"]
        s3_client.head_object(Bucket=BUCKET, Key=s3_key)

        return s3_client.generate_presigned_url(
            ClientMethod="get_object",
            Params={"Bucket": BUCKET, "Key": s3_key},
            ExpiresIn=settings.file_url_expiry_seconds,
        )
    except ClientError as exc:
        logger.error("S3 error fetching presigned URL for %s: %s", file_id, exc)
        return None
    except Exception as exc:
        logger.error("Unexpected error generating presigned URL for %s: %s", file_id, exc)
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def create_pdf_report(content: str) -> dict | None:
    """Convert LLM Markdown output to a PDF, upload to S3, and return file info.

    Args:
        content: Raw Markdown string produced by the BI report writer LLM.

    Returns:
        A dict with ``fileId``, ``fileName``, and ``sizeInBytes`` keys, or
        ``None`` if generation fails.
    """
    file_id = str(uuid.uuid4())
    base_dir = Path("/tmp") / file_id
    original_dir = base_dir / "original"
    os.makedirs(original_dir, exist_ok=True)

    filename = "Analysis Report.pdf"
    s3_key = f"{file_id}/original/{filename}"
    original_file_path = original_dir / filename

    try:
        doc = SimpleDocTemplate(
            str(original_file_path),
            leftMargin=40,
            rightMargin=40,
            topMargin=40,
            bottomMargin=40,
        )

        elements = _build_pdf_elements(content, doc)
        doc.build(elements)

        s3_client.upload_file(str(original_file_path), BUCKET, s3_key)
        logger.info("PDF uploaded to S3: %s", s3_key)

        presigned_url = _get_presigned_url(file_id)
        if not presigned_url:
            logger.warning("PDF uploaded but presigned URL could not be generated for %s", file_id)
            return None

        return {
            "fileId": file_id,
            "fileName": filename,
            "sizeInBytes": os.path.getsize(str(original_file_path)),
        }

    except Exception as exc:
        logger.error("PDF generation failed for %s: %s", file_id, exc)
        if original_file_path.exists():
            try:
                os.remove(original_file_path)
            except OSError:
                pass
        return None


def _build_pdf_elements(content: str, doc: SimpleDocTemplate) -> list:
    """Parse Markdown *content* and produce a list of ReportLab flowables."""
    # Use a mutable list so _append_text_block can update the flag in-place.
    is_first_section_ref = [True]
    elements: list = []

    # Extract and remove the # title
    title_match = re.search(r"^\s*#\s+(.*?)\s*$", content, flags=re.MULTILINE)
    report_title = title_match.group(1).strip() if title_match else "Analysis Report"
    content = re.sub(r"^\s*#\s+.*?$", "", content, count=1, flags=re.MULTILINE)

    # Strip the ```suggestions block — it is not included in the PDF
    content = re.sub(
        r"```suggestions\s*.*?```",
        "",
        content,
        flags=re.DOTALL | re.IGNORECASE,
    )

    # Strip vega-lite blocks — raw JSON should not appear as text in the PDF
    content = re.sub(
        r"```vega-lite\s*.*?```",
        "",
        content,
        flags=re.DOTALL | re.IGNORECASE,
    )

    # Cover page
    elements.append(Spacer(1, doc.height / 2 - 40))
    elements.append(Paragraph(report_title, cover_style))
    elements.append(PageBreak())

    # Split on Mermaid fences: odd indices are Mermaid code, even are text
    parts = re.split(r"```mermaid\s*(.*?)```", content, flags=re.DOTALL | re.IGNORECASE)

    for idx, part in enumerate(parts):
        if idx % 2 == 0:
            _append_text_block(part, elements, is_first_section_ref)
        # else:
        #     Mermaid chart rendering is temporarily disabled.
        #     Uncomment the line below to re-enable chart images in the PDF.
        #     _append_mermaid_block(part, elements, doc)

    return elements


def _append_text_block(text: str, elements: list, is_first_section_ref: list) -> None:
    """Append ReportLab flowables for a plain-text/Markdown block.

    *is_first_section_ref* is a one-element list used as a mutable flag so that
    changes to the "first section" state persist across calls.
    """
    text = text.strip()
    if not text:
        return

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue

        line = _markdown_to_reportlab(line)

        if line.startswith("# "):
            # H1 was rendered on the cover page
            continue
        elif line.startswith("## "):
            if not is_first_section_ref[0]:
                # 3 blank lines between sections instead of a page break
                elements.append(Spacer(1, 14))
                elements.append(Spacer(1, 14))
                elements.append(Spacer(1, 14))
                # elements.append(PageBreak())  # page break disabled
            is_first_section_ref[0] = False
            elements.append(Paragraph(line[3:], heading2_style))
            elements.append(Spacer(1, 10))
        elif line.startswith("### "):
            elements.append(Paragraph(line[4:], heading3_style))
        elif line.startswith("- "):
            elements.append(Paragraph(line[2:], bullet_style, bulletText="•"))
        else:
            elements.append(Paragraph(line, body_style))

    elements.append(Spacer(1, 10))


def _append_mermaid_block(mermaid_code: str, elements: list, doc: SimpleDocTemplate) -> None:
    png_file = None
    mmd_file = None
    try:
        png_file, mmd_file = render_mermaid_to_png(mermaid_code)
        img = fit_image(png_file, max_width=doc.width - 20, max_height=350)
        img.hAlign = "CENTER"
        elements.append(img)
        elements.append(Spacer(1, 15))
    except Exception as exc:
        logger.warning("Mermaid render error: %s", exc)
        elements.append(
            Paragraph(f"<b>Failed to render Mermaid diagram:</b><br/>{exc}", body_style)
        )
        elements.append(Spacer(1, 10))
    finally:
        for path in filter(None, [png_file, mmd_file]):
            if os.path.exists(path):
                try:
                    os.remove(path)
                except OSError:
                    pass
