```mermaid
barChart
title "Bookings by Market Segment | Distribution Channel"
x-axis ["Online TA | TA/TO","Offline TA/TO | TA/TO","Direct | Direct","Corporate | Corporate","Groups | Corporate","Direct | TA/TO"]
y-axis "Bookings"
bar [394,141,117,11,8,1]
```